name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome106-ff106
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run cloud
          start: npm cloud
          browser: chrome